- hosts: localhost
  gather_facts: false
  become: true
  become_user: root

  vars_prompt:
    - name: "package"
      prompt: "Quel paquet voulez-vous installer"
      private: no
    - name: "version"
      prompt: "Quelle version?"
      default: "latest"
      private: no    

  tasks:
    - name: install package
      apt:
        name: "{{ package }}"
        state: "{{ version |default('latest') }}"
        with_items:
          - sl 
          - vim
          - nginx